### ISSUE TITLE
npm-check does not discover `require.resolve`

### ISSUE THREAD

**Issue by khanh-nguyen** [dylang/npm-check#10]
If you use `require.resolve('module-name')`, `npm-check` won't discover it.

**Comment by jameswomack** [comment]
Hmm. `resolve` is for discovering the path to the module, not for actually loading it. Do you mean:
```
var pathToFooModule = require.resolve('foo');
var fooModule = require(pathToFooModule);
fooModule.doSomething();
```

**Comment by khanh-nguyen** [comment]
@jameswomack You're right. The way it was used in the repo I was looking at was not very straightforward. `require.resolve` was used to get the paths of modules, which are used in webpack config file. Then, module is required using `require(<%= JSON.stringify(module-path) %>)`.
So, it's not really the problem with `require.resolve`.

**Comment by dylang** [comment]
Hi @khanh-nguyen, I'm closing this old ticket, let me know if there's still an issue.
