### ISSUE TITLE
Add incorrectly unused modules

### ISSUE THREAD

**Issue by Calvein** [dylang/npm-check#100]
I'm not sure if there is any other use cases but I came across this with browserify, since you don't have to require the transforms/plugins, it's not getting picked up, e.g:

```js
import babelify from 'babelify'
browserify('index.js').transform(babelify)
// Is the same as
browserify('index.js').transform('babelify')
```

I'm fine with requiring my transforms modules so it's more of an FYI that an issue.

**Comment by dylang** [comment]
Thanks, I'm going to consider this a dup of #71. Let me know if you think otherwise.

**Comment by Calvein** [comment]
I was thinking of it too but it's actually the opposite, it's packages, that aren't properly imported/required, that are showing up as `NOTUSED?` while in fact they are used.

**Comment by Calvein** [comment]
But it can be fixed the in the same way as #71, with a package.json & CLI option to add them.

**Comment by dylang** [comment]
I think it's the same. The problem is that [depcheck](https://github.com/depcheck/depcheck) looks for `require` and `import` statements, and doesn't know about `transform` statements.

**Comment by lijunle** [comment]
@Calvein I am the maintainer of depcheck. Please open an issue in depcheck and detail your problem about babelify.
