### ISSUE TITLE
Checking process blocked mysterious

### ISSUE THREAD

**Issue by micooz** [dylang/npm-check#105]
After issue `npm-check`, the process start checking, but blocked on random dependency.

e.g.

> $ npm-check
> [] Checking registry for helmet - complete.

Checking always...

Maybe it's not my network problem.

**Comment by dylang** [comment]
Interesting, thanks for creating an issue @micooz.  

The one it is listing isn't necessarily the one it is blocked on because all of the network connections are run at once.

* Are you able to share your `package.json` so I can try it?
* Are you just using node modules from the public registry or are you using a private registry, github, or something else?

**Comment by micooz** [comment]
Hi, @dylang. I'm using another public registry, but after I change it to npm official, the process blocked again.

Here is my `package.json`:

[package.txt](https://github.com/dylang/npm-check/files/197911/package.txt)

Sorry for github don’t support `json` file type. Please change it to `.json` manually.

**Comment by dylang** [comment]
I'm able to use your `package.json` file without problems. 

<img width="768" alt="screen shot 2016-03-31 at 4 51 38 pm" src="https://cloud.githubusercontent.com/assets/51505/14190462/e02fbd5c-f760-11e5-9939-222e6f69e5ed.png">

* What version of `node` are you using? 
* How's your internet connection?
* What was the other public registry you were using?

**Comment by micooz** [comment]
Hello, @dylang

* My node version is `v5.9.1`
* I'm China, internet connection broken from time to time, but `shadowsocks` is a workaround
* I'm using `registry=https://registry.npm.taobao.org/` to speed up my npm process

**Comment by dylang** [comment]
Great, thanks @micooz for all that information. 

Next version I'll added a concurrency check so not to open so many connections at the same time. Hopefully that will help.
