### ISSUE TITLE
`npm shrinkwrap` error

### ISSUE THREAD

**Issue by nikolay** [dylang/npm-check#108]
```
$ npm shrinkwrap
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/user/Projects/project/.env/pyenv/versions/3.5.1/envs/projects/bin/node" "/Users/user/Projects/project/.env/pyenv/versions/project/bin/npm" "shrinkwrap"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: node-sass@^3.4.0, required by depcheck@0.6.2
npm ERR! peer invalid: typescript@^1.8.0, required by depcheck@0.6.2
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Projects/project/npm-debug.log
```

**Comment by lijunle** [comment]
Hmm...

Could you please skip it, because they are just peer dependencies.

**Comment by nikolay** [comment]
@lijunle How can I skip those during `npm shrinkwrap`?

**Comment by lijunle** [comment]
It seems a bug from NPM: https://github.com/npm/npm/issues/10836 :cry:

**Comment by lijunle** [comment]
@dylang I could like to remove these two peer dependencies from depcheck to unblock @nikolay :smile:

**Comment by dylang** [comment]
Thanks @lijunle!

**Comment by lijunle** [comment]
depcheck@0.6.3 is out to resolve this. Could you please run `npm i -g npm-check` and try again.

/cc @antoniobrandao

**Comment by dylang** [comment]
Thanks @lijunle!

**Comment by dylang** [comment]
Updated in `npm-check`. You'll need to update `npm-check`, which you can do using `npm-check`. :smile:

Let us know if you are still having problems after this.

**Comment by antoniobrandao** [comment]
All seems fine now! Using node 5.10.0 npm 3.8.3
