### ISSUE TITLE
[Feature] Integrate npmsearch.com scores

### ISSUE THREAD

**Issue by petermikitsh** [dylang/npm-check#111]
It would be nice to provide the npmsearch.com score, or rather, a warning for a specific module if the score is low.

As a developer, I want to be sure I am using projects that are well tested, that way I can be confident in depending on a module.

Ideally the developer should vet each module they use as they are added, but on existing projects it's considerable work to go back and analyze all of your modules for quality.

**Comment by dylang** [comment]
Hi @petermikitsh, thanks for your suggestion. 

This is a cool idea, but I'm not sure if it belongs in this tool which focuses on out-of-date dependencies. How would it output? Today we only output dependencies that are outdated or not used. This sounds like you would want all dependencies listed, or maybe all those with a low score. I also don't think a low score is necessarily bad - all new modules are going to have low score even if they are the best at what they do.

If you make `npm-check-scores` I am happy to link to it in the README!

**Comment by petermikitsh** [comment]
I don't think it's viable or useful enough as a separate module. Thanks for your reply!
