### ISSUE TITLE
Dependecies ok?

### ISSUE THREAD

**Issue by antoniobrandao** [dylang/npm-check#114]
└─┬ npm-check@5.0.1
  ├── UNMET PEER DEPENDENCY node-sass@^3.4.0
  └── UNMET PEER DEPENDENCY typescript@^1.8.0

npm WARN depcheck@0.6.2 requires a peer of node-sass@^3.4.0 but none was installed.
npm WARN depcheck@0.6.2 requires a peer of typescript@^1.8.0 but none was installed.

**Comment by dylang** [comment]
I feel that this is a [known issue with the dependency depcheck](https://github.com/depcheck/depcheck/issues/130), but I could include these two dependencies to avoid this warning. I haven't had requests for typescript or sass support so I haven't included them.

**Comment by antoniobrandao** [comment]
I don't use node-sass neither node-sass in my projects btw
