### ISSUE TITLE
npm-check is not accurate

### ISSUE THREAD

**Issue by rafaelfragosom** [dylang/npm-check#116]
I created a branch to test npm-check inside my project, and it pointed out some modules that I was not using, so I trusted npm-check and removed the modules from my package.json, and, for my surprise, I was actually using these modules, explicitly inside my code.

Also, I may not seen it, but is there a place specifying the npm and node version compatible with this module? I had to switch to 4.x to make it work. It doesn't work with 0.12.x.

Thanks

**Comment by dylang** [comment]
> it pointed out some modules that I was not using

This is what it says today:
```
Possibly not referenced in the code.
```
This is meant to imply that it is not a guarantee, but understand if that that is not clear from the text. Do you have a suggestion for what the text should say to make this more clear?

> I was actually using these modules, explicitly inside my code.

`npm-check` use [depcheck](https://github.com/depcheck/depcheck) to figure out what is being used. Do you want to check out that package and see if it's a bug there that can be fixed?

> a place specifying the npm and node version compatible with

You are correct, I forgot to mention this in the readme, thanks for bringing it up! It only requires Node 4, not a specific version of `npm`.

**Comment by rafaelfragosom** [comment]
Thanks for the quick response. Maybe something like:

> Possibly not referenced in the code. Please, double check your code before any changes.

Maybe too big?? But something in that direction, asking the user to double check the code.

I just saw depcheck and here's what they added to the README:

> The logic of a special is not perfect. There might be false alerts. If it happens, please open an issue for us.

But they also have a `special` argument to check for dependencies being used inside grunt, mocha, webpack... and in this case, some of the modules that npm-check reported were in this scenario.

**Comment by lijunle** [comment]
Hi, @rafaelfragosom 

I am the maintainer for depcheck. There is no magic to detect an package is used in code. We find some patterns and create some rules for them. The logic is not prefect. We want to improve it. For the false alert cases, could you please open an issue in depcheck. I will take a look when I have time.

Thanks for reporting!

**Comment by rafaelfragosom** [comment]
@lijunle Thanks. I'll send you the full report and project structure in a few hours.

**Comment by dylang** [comment]
I changed the text significantly. 
<img width="1084" alt="screen shot 2016-04-01 at 5 11 44 pm" src="https://cloud.githubusercontent.com/assets/51505/14220252/d8cd2a32-f82c-11e5-9acb-dc6c66ed25b1.png">

If this is still confusing please open a new issue, thanks!

**Comment by rafaelfragosom** [comment]
@dylang Perfect!

Thanks for the update, I'm gonna send my report to depcheck and investigate it with them.
