### ISSUE TITLE
Potential Logical Mismatch 

### ISSUE THREAD

**Issue by jameswomack** [dylang/npm-check#12]
If you have modules in your node_modules folder that aren't in your package.json file, it will warn you if they are not up to date, but not warn you if they aren't used anywhere. This seems a mismatch to other behavior. If the module *is* in your package.json file it will warn you that it's not used.

**Comment by dylang** [comment]
Good find, thanks!

**Comment by dylang** [comment]
I think this has been fixed, thanks for the report!

<img width="585" alt="screen shot 2015-08-29 at 7 22 16 pm" src="https://cloud.githubusercontent.com/assets/51505/9564876/5c8518b6-4e83-11e5-8920-762736725343.png">
