### ISSUE TITLE
npm-check in project root falsely reports path as not being used

### ISSUE THREAD

**Issue by dcorns** [dylang/npm-check#137]
It appears that when assigning multiple variables using comas masks a module's use from the program.
var express = require('express'), path = require('path');
npm-check indicates that path is not being used.

**Comment by lijunle** [comment]
@dcorns do you install a `path` package in your `package.json` file?

**Comment by dcorns** [comment]
Yes, under devDependencies

**Comment by lijunle** [comment]
Hmm...

I want to make it clear. Why do you use the [npm path](https://www.npmjs.com/package/path) instead of the node.js build in one?

**Comment by dodekeract** [comment]
I think this can be closed. I'm quite sure @dcorns just made a mistake (easy to do if you don't know path is in the standard library).

**Comment by LinusU** [comment]
Closing for now, probably caused by `path` being a dependency whilst also being a built-in module in Node core
