### ISSUE TITLE
depcheck options 'ignoreMatches'

### ISSUE THREAD

**Issue by eldinoyev** [dylang/npm-check#145]
In lib/in/get-unused-packages.js:33 I see the following options for depcheck

``` js
ignoreMatches: [
    'gulp-*',
    'grunt-*',
    'karma-*',
    'angular-*',
    'babel-*',
    'metalsmith-*',
    'grunt',
    'mocha',
    'ava'
]
```

are those actually supposed to get ignored or is this there for some other reason?

**Comment by lijunle** [comment]
The reason is to simply skip false positives.

**Comment by eldinoyev** [comment]
Does this mean "babel-core", "babel-cli", etc. should not show up in the listed dependencies to update?"

**Comment by lijunle** [comment]
I think the list is only for unused dependencies check. Could better to get a confirm form @dylang .
