### ISSUE TITLE
Output truncated in Node.js 6

### ISSUE THREAD

**Issue by LinusU** [dylang/npm-check#149]
In Node.js 6 the output is sometimes (seems to happen when there is more than a few lines in the output) truncated because the process is killed before process.stdout is flushed.

The fix for this is to stop using `process.exit()` and instead use `process.exitCode = `.

**Comment by davej** [comment]
Also seeing this.

**Comment by wtr7** [comment]
Having the same issue

**Comment by lijunle** [comment]
@LinusU You could better to ping @dylang via email. Got it from git commits.

**Comment by LinusU** [comment]
Fixed in 5.2.2
