### ISSUE TITLE
Option to not upgrade version of packages at package.json

### ISSUE THREAD

**Issue by miduga** [dylang/npm-check#156]
Hi there. First of all, amazing app! In our company we're using it but we're facing a minor problem. As we want to update our packages by using sometimes semver with major and features versions, npm-check is overwritting our package configuration to follow this pattern.

Our package.json before npm-check:
```
"@company/package-1": "6",
"@company/package-2": "3.2",
```

After execution with:
```
"@company/package-1": "^7.0.1",
"@company/package-2": "^3.4.2",
```

Desired:
```
"@company/package-1": "7", // if the package was updated with npm-check and a major is new
"@company/package-2": "3.4", // if the package was update with npm-check and feature is new
```

So, we would like a parameter in order to avoid npm-check to overwrite the semver pattern follow in each package. Something similar as -E param but not for saving the exact version but the exact semver followed before. :)

**Comment by amilajack** [comment]
Fixed in https://github.com/dylang/npm-check/pull/142
