### ISSUE TITLE
Unused check doesn't understand `browser` field

### ISSUE THREAD

**Issue by kornelski** [dylang/npm-check#157]
In [package.json](https://github.com/visionmedia/superagent/blob/master/package.json) I have:

``` js
  "browser": {
    "emitter": "component-emitter"
  },
```

and code uses `require('emitter')`.

> npm-check
> 
> component-emitter   😕  NOTUSED?  Still using component-emitter?
>                                  Depcheck did not find code similar to require('component-emitter') or import from 'component-emitter'.

**Comment by lijunle** [comment]
Hi, @pornel How does this work? You declare `emitter` in `browser` then you can *require* it? Which package manager tool are you using?

**Comment by pornel** [comment]
It's for browserify and webpack. It swaps/renames modules when browser build is made, allowing different implementations for browser and node.

So we have `require('emitter')` in source code and it either loads `emitter` in node, or `component-emitter` in browserify.

**Comment by lijunle** [comment]
@pornel I cannot find the related webpack document. Could you please give me a link?

**Comment by pornel** [comment]
I don't know if it's documented, but it I assume it works, since superagent uses this field and works with webpack :)

**Comment by pornel** [comment]
These maybe? 

https://webpack.github.io/docs/configuration.html#resolve-packagemains
https://github.com/defunctzombie/package-browser-field-spec
