### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by bradjohnwoods** [dylang/npm-check#159]
this module just doesn't work at all for me..

I know I have some modules that have out of date dependencies, npm-check didn't find any of them. Also it states I'm not using 'htmlmin' even though my gulp file is using it.

**Comment by LinusU** [comment]
> I know I have some modules that have out of date dependencies, npm-check didn't find any of them.

That's not good at all, can you post which dependencies?

> Also it states I'm not using 'htmlmin' even though my gulp file is using it.

How does the code look that requires in `htmlmin`?

**Comment by dooso** [comment]
when i run `npm-check -ug`, it deleted ALL my global node modules,  include NPM !!! WTF

**Comment by amilajack** [comment]
Closing until more information can be provided
