### ISSUE TITLE
Support ES6 import

### ISSUE THREAD

**Issue by MoOx** [dylang/npm-check#17]
That would be nice.
I think right now, it's not supported since almost all my modules imported via es6 module syntax are listed as unused.

**Comment by dantman** [comment]
This is related to an issue in depcheck.

See rumpl/depcheck#21

**Comment by aamirafridi** [comment]
:+1: for this

**Comment by dylang** [comment]
As soon as we get in https://github.com/rumpl/depcheck/pull/29 in I'll update the dependency.

**Comment by rkoberg** [comment]
This looks like it has been fixed? https://github.com/rumpl/depcheck/pull/29

**Comment by dylang** [comment]
Thanks @rkoberg, it hasn't been merged and published to npm yet.

**Comment by woodb** [comment]
I've submitted PR #42 that uses a fork of `depcheck` which includes the merging of the PR mentioned above.

**Comment by dylang** [comment]
This is now fixed, thanks for your help everyone! `npm -g i npm-check` to get `4.1.0` with the support for es6 `import`.
