### ISSUE TITLE
Fails with "package.json was not found at" $HOME under Cygwin

### ISSUE THREAD

**Issue by emigenix** [dylang/npm-check#176]
Running an otherwise working *node/npm* and *npm-check* installation under latest Cygwin on W8.1, results in the following error. 

```sh
$ node -v && npm -v && npm-check --version
v6.4.0
3.10.3
5.2.3

$ npm-check
A package.json was not found at C:\cygwin64\home\xxxx\package.json
For more detail, add `--debug` to the command
```
PS. Do add the `--version` flag to your `npm-check` flag list.

**Comment by LinusU** [comment]
Which directory are you running it in? Is there a package.json in the current directory?

**Comment by emigenix** [comment]
@LinusU `$HOME` (Did you read the title?) There is no *package.json* there, why should there be? I was under the impression that `npm-check` (without `-g` flag) should find all local installations. Perhaps that's not what was intended? If, so please update the error text to something more informal and/or make a check if user is in someplace, where there should be no node modules/installations, like in `$HOME` and `%APPDATA%` etc.

**Comment by LinusU** [comment]
What do you mean with "all local installations". Where do you have modules installed that you expect npm-check to find?

**Comment by emigenix** [comment]
@LinusU I guess I was having unusual expectations, so I'm closing this issue as not applicable. Optionally, you might consider changing the error messages to something along the lines:
```
$ npm-check
A package.json was not found at C:\cygwin64\home\xxxx\package.json
Make sure you are specifying the location of the npm package you need to check. 
For more detail, add `--debug` to the command
```
