### ISSUE TITLE
Colors are not shown

### ISSUE THREAD

**Issue by emigenix** [dylang/npm-check#177]
Running *npm-check* in Cygwin, breaks coloring. I.e. `ls` and [`colortest.sh`](https://github.com/mikker/dotfiles/blob/master/bin/colortest.sh) correctly show all ANSI colors, but npm-check doesn't. 

**EDIT**

[Apparently](https://github.com/dylang/npm-check/blob/master/lib/state/state.js#L14) colors are off by default. It now works partially by supplying `npm-check --color`. (Again, please update the `npm-check --help` text.) But the colors are wrong and look nothing like in the README.

**Comment by LinusU** [comment]
We are using standard [chalk](https://github.com/chalk/chalk), could you please open an issue with them?

**Comment by amilajack** [comment]
Closing due to no response
