### ISSUE TITLE
Having trouble with npm-check -u

### ISSUE THREAD

**Issue by ruben-h** [dylang/npm-check#18]
Hi!

I was trying out this npm package, but I'm having trouble with using `npm-check -u` to select packages to update.

The "caret" used to navigate and select packages, disappears when I move it up or down so much that scrolling the list is started.

I'm using zsh with agnoster theme in iterm2.

Regards 
Ruben

**Comment by dylang** [comment]
Awesome, I'm not the only one having this problem and I'm not the only one using `zsh` in `iterm2`!

This is a problem with [Inquirer.js](https://github.com/SBoudrias/Inquirer.js). 

I have a fix but it's incomplete. Do you want to help finish it?  https://github.com/SBoudrias/Inquirer.js/pull/181

**Comment by ChiperSoft** [comment]
I've also been having this problem for a long time, can only update one page of selections at a time (why is the list so short?)

**Comment by tarlepp** [comment]
Yeah, I have same issue with ```gnome-terminal```, any updates on this one?

**Comment by dylang** [comment]
I have an update working locally and will deploy soon.

**Comment by dylang** [comment]
I've pushed a new version with customized update UI code that should fix this problem!
