### ISSUE TITLE
`--skip-unused` causes used modules that are missing from package.json to be missed.

### ISSUE THREAD

**Issue by jwietelmann** [dylang/npm-check#181]
Without flag:

<img width="790" alt="screen shot 2016-09-02 at 5 09 21 pm" src="https://cloud.githubusercontent.com/assets/550889/18219559/254dc62e-7130-11e6-8932-f4377d33765b.png">

With flag:

<img width="357" alt="screen shot 2016-09-02 at 5 10 02 pm" src="https://cloud.githubusercontent.com/assets/550889/18219558/254976f0-7130-11e6-9633-96d5d54c6522.png">

**Comment by amilajack** [comment]
Fixed in https://github.com/dylang/npm-check/pull/142
