### ISSUE TITLE
Search in all js files from the module

### ISSUE THREAD

**Issue by IonicaBizau** [dylang/npm-check#19]
...not only in the main one. The common use-case is when I have the `bin` directory containing a command line tool. It could require things that are not used in the library (e.g. command line parser).

Running `npm-check` gives me the following:

![image](https://cloud.githubusercontent.com/assets/2864371/8186655/3a41ce02-1454-11e5-9174-d1f96ba613c1.png)

They are used in the `bin/something`.

Nice tool, btw! :smile:

**Comment by aarr0n** [comment]
:+1: for this. Being able to pass a folder glob as an additional option would be awesome.

**Comment by dylang** [comment]
We are checking your `bin` directory but it's ignoring files that don't end in `.js`.

A workaround and general best practice is to keep the file without an extension to just require the real code which has the `.js` extension. 

Example:
```js
#!/usr/bin/env node
require('../lib/cli');
```

**Comment by IonicaBizau** [comment]
@dylang Thanks for the response. Is it possible to specify the custom file (`bin/foo`) somehow?

**Comment by dylang** [comment]
@IonicaBizau I've created a new ticket for this: #32.

**Comment by IonicaBizau** [comment]
:+1: Thanks!
