### ISSUE TITLE
looks horrible in Windows

### ISSUE THREAD

**Issue by dylang** [dylang/npm-check#2]
At least with default colors it's just ugly.

The interactive UI works in Windows but it's difficult to see when a module is selected to install.

**Comment by kitze** [comment]
It doesn't  look horrible, but it doesn't work in cmd, cygwin, cmder, webstorm terminal, i've tried everything but when i go with the arrows up and down it just loses track of the arrow (currently selected item) and i don't know which item i'm checking or unchecking.

Here's a gif: http://i.imgur.com/U4ujWKJ.gif

**Comment by mrmartineau** [comment]
@dylang I have similar issues on my Mac with iTerm & Terminal, see my screencast here http://quick.as/3479sr6o

It loses track of the arrow and is limited to about 6 lines despite the window being taller

**Comment by dylang** [comment]
@mrmartineau yup, I have that problem too. It's a problem with https://github.com/SBoudrias/Inquirer.js - do you want to create an issue there with your screencast?

**Comment by mrmartineau** [comment]
@dylang I have had a look through the existing issues on Inquirer.js and noticed your PR (https://github.com/SBoudrias/Inquirer.js/pull/181). Is that supposed to fix this issue?

**Comment by dylang** [comment]
It only addresses the issue in that usually you won't need to scroll.

**Comment by rictorres** [comment]
my main problem on windows is _contrast_

![image](https://cloud.githubusercontent.com/assets/351568/7879404/70d236a4-05f0-11e5-9942-1b3ba1350a06.png)

i'm gonna do some tests, perhaps i can come up with a PR if that's ok :)
