### ISSUE TITLE
Looks to the wrong registry for scoped packages

### ISSUE THREAD

**Issue by moll** [dylang/npm-check#21]
Hey,

I'm using NPM's support for directing some specific scopes to different registries. Given the error below it seems to be npm-check is still looking for that package in the main registry.

```
                            �  NPM ERR!  https://registry.npmjs.org/ returned Not found : @some_scope
```

Cheers

**Comment by dylang** [comment]
Good find, I haven't used any scoped packages yet. I'll give it a look.

**Comment by moll** [comment]
Cool.

You intentionally use `String.prototype.replace` with a string arg there? That's not global replace in that case. ;-)

**Comment by dylang** [comment]
Yeah, good code review comment. I was thinking there should only ever be one `/` in there, and if there are more than one then `npm` added a new feature that we might not support yet, but I should change it to be safe.

**Comment by dylang** [comment]
Actually that code is gone, replaced with Sindresorhus's [package-json](https://github.com/sindresorhus/package-json).

https://github.com/dylang/npm-check/blob/master/lib/npm/get-npm-info.js#L10
