### ISSUE TITLE
Can't install on Node >7

### ISSUE THREAD

**Issue by simlevesque** [dylang/npm-check#222]
Here's my log for proof : 

user@A1 ~/project> npm i --save-dev npm-check
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"7.6.0","npm":"4.4.1"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"4.4.1","node":"7.6.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-03-15T15_44_40_843Z-debug.log

**Comment by amilajack** [comment]
> npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"7.6.0","npm":"4.4.1"})

This is an issue with the `got` package

**Comment by simlevesque** [comment]
Yeah but I still cannot install your app on Node 7 because of it...

**Comment by amilajack** [comment]
I think you should make an issue in the got repo or the npm package that is using got. Its good to have this kind of validation. Its just that the validation needs to be fixed

**Comment by simlevesque** [comment]
Their issue is fixed, it's just that one of your dependencies uses an old version of got that's not fixed.
