### ISSUE TITLE
New version doesn't show package link anymore

### ISSUE THREAD

**Issue by steverandy** [dylang/npm-check#234]
With the recent update (v5.4.4), I noticed that the link for a package is not available anymore.
Is this a bug or an intended change?

**Comment by joeycozza** [comment]
the "homepage" key is there for v5.4.0, and it is not anymore in v5.4.2.  (it looks liek 5.4.1 wasn't ever published to npm)

I'll keep doing some digging and see if I can narrow down which commit did it.

**Comment by joeycozza** [comment]
So there was a breaking change in the behavior of the module "package-json" dealing with meta-data and abbreviated meta-data.

https://github.com/sindresorhus/package-json/commit/282119311c97b5e7ebd9f61372635f61cfb5fce3

This was in the commit message 

> - Return an abbreviated metadata by default. Use the `fullMetadata` option to get back the previous behavior.

So if we want to get the old behavior back, it wouldn't be too hard (I'll make a PR for it)

**Comment by joeycozza** [comment]
This should be closed as the fix was merged and released in v5.4.5

**Comment by LinusU** [comment]
Thanks @joeycozza!
