### ISSUE TITLE
Feature Request: link to changelog

### ISSUE THREAD

**Issue by gotbahn** [dylang/npm-check#238]
Thank you for such a nice tool. I noticed that links to repo are missing in new versions. It was pretty handy to have it since usually I'm checking changelogs before update something.
But what could be even better is provide a link to changelog to have it right away.

**Comment by luftywiranda13** [comment]
Yeah it'll be a great addition

**Comment by karfau** [comment]
This would be such a big improvement.
We could check if there is a changelog in the package (or in the repo?) and if not link to the [releases](https://github.com/dylang/npm-check/releases) "folder" of the repo.
This would of course not work for something like `@types/...` but maybe there is even a clever/generic  way to deal with those...
Happy to contribute to this part if I get some hint how it should look like and where to tart looking in the code.

**Comment by lydell** [comment]
The [npm-upgrade](https://github.com/th0r/npm-upgrade) tool is pretty good at guessing changelog URLs. Maybe inspiration can be taken from there?

https://github.com/th0r/npm-upgrade/blob/6cb7a30f57f022b5831a35189c56835c60d8d79f/src/changelogUtils.js

**Comment by rhucle** [comment]
PR welcome?
