### ISSUE TITLE
npm v3 compatibility

### ISSUE THREAD

**Issue by lukeapage** [dylang/npm-check#24]
It seems that because npm v3 has a flat structure, you get too many results back from npm-check.

I guess it needs to look at the top level dependencies by scanning the package.json?

**Comment by dylang** [comment]
Yeah, this is going to change how a bunch of things work. Thanks for the reminder about this.

**Comment by goffreder** [comment]
Maybe an option to disable automatic --save (or --save-dev) when using the interactive update could be useful, the first time I tried to update with npm@3 I cluttered my package.json file.

**Comment by dylang** [comment]
Fixed for `npm@3`!
