### ISSUE TITLE
[discussion] [Feature request] Add command to install if library not installed

### ISSUE THREAD

**Issue by hellboy81** [dylang/npm-check#25]
- Add command to install if library not installed
Sample:
```js
mocha                   - MISSING!  In package.json but not installed.
                              npm i mocha --save-dev to install
```

**Comment by hellboy81** [comment]
```sh
npm i mocha --save-dev to install
```

This line should be added

**Comment by dylang** [comment]
I think it does what you are asking when you use `npm-check -u`:

<img width="404" alt="screen shot 2015-08-29 at 6 16 06 pm" src="https://cloud.githubusercontent.com/assets/51505/9564596/1a162672-4e7a-11e5-8cc9-decc94493197.png">
