### ISSUE TITLE
namespaced packages?

### ISSUE THREAD

**Issue by jliebrand** [dylang/npm-check#256]
First of all: thanks for a great package! It's super useful and really helps us keep on top of our dep management!

One quick question. We have a few dependencies that use namespaces like:
https://www.npmjs.com/package/@mapbox/vector-tile

resulting in "@mapbox/vector-tile" in our package.json but "import VectorTile from 'vector-tile';" in our code.
Which trips up npm-check a little

Any plans to include knowledge about namespaces in npm-check?

**Comment by LinusU** [comment]
Shouldn't that be `import VectorTile from '@mapbox/vector-tile'` in your code?

I'm quite positive that this has worked for me, at least using `require('@filestore/disk')`...

**Comment by jliebrand** [comment]
doh - you're absolutely right... ignore me :-)
