### ISSUE TITLE
npm version issue on Windows?

### ISSUE THREAD

**Issue by warrenhales** [dylang/npm-check#27]
Just a quick qualification ... I am new to node, npm, github and open source projects in general.

### Issue
On Windows i have updated npm to version 2.13.0 but npm-check thinks the latest version is 2.11.3.

On Windows

`> npm list -g --depth=0 `

returns: 
```
C:\Users\Warren\AppData\Roaming\npm
├── bower@1.4.1
├── gulp@3.8.11
├── npm@2.13.0
...
```

But:

`> npm-check -g`

returns:
```
npm   ?  MINOR UP  Minor update available: https://docs.npmjs.com/
                   npm install --save npm@2.13.0 to go from 2.11.3 to 2.13.0
```

### Other Details

The Windows node installer (.msi) installs npm in the same directory as it installs node.  

In my case it installed npm 2.11.3 to `C:\Program Files\nodejs\node_modules\npm`.

I then updated npm using:

`npm -g install npm@latest`

And it installed npm 2.13.0 to %APP_PATH% which in my case is `C:\Users\Warren\AppData\Roaming\npm`

So there are two versions of npm on my computer.  

This issue is described further here:  
https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

It appears that npm-check is checking (using?) the version installed by the node installer (2.11.3).  While powershell is using the updated version installed via npm itself (2.13.0)

*NOTE:* I did also test out Option 2 described in the link above and had the same results.

**Comment by warrenhales** [comment]
Dylan let me know I can see which directory npm-check uses using this cmd:

`>npm config get prefix`

My results were: 

```
PS C:\> npm config get prefix
C:\Users\Warren\AppData\Roaming\npm
```

Interestingly, it pointed to the directory where the latest (2.13.0) was installed.  But npm-check still reports that npm is out of date at version 2.11.3.

**Comment by dylang** [comment]
I've changed how I find global modules using a package called `global-modules` - hopefully this fixed the problem, if not please let me know.
