### ISSUE TITLE
Can't install. Don't ever use timed-out anymore.

### ISSUE THREAD

**Issue by terrybleger** [dylang/npm-check#271]
```npm -g install npm-check``` won't work anymore. I think the author/maintainer for timed-out was already dead. Please fix this asap.

**Comment by LinusU** [comment]
> won't work anymore

works for me

> I think the author/maintainer for timed-out was already dead

I don't quite understand what you mean here, could you elaborate?

> Please fix this asap.

Could you post the error you are getting?

**Comment by woodyrew** [comment]
Installing packages globally isn't really necessary with npm >= 5.
You can run with: `npx npm-check`.

`npm install -g npm-check` works fine for me.

**Comment by LinusU** [comment]
closing until we receive more info
