### ISSUE TITLE
Deps used in files sans .js extension aren't found

### ISSUE THREAD

**Issue by jameswomack** [dylang/npm-check#28]
# How to reproduce

1. Create a new project
2. `npm i debug -S`
3. Use "debug" in a file at the path bin/www (bin is a folder, www is the filename)
4. Run npm-check

**Comment by dylang** [comment]
In your `www` file (or any without an extension) have one line:
```js
module.exports = require('./www.js'`);
```

And put your code in `www.js` instead.

I don't think it make sense to check *all* files. That would mean checking css, images, files in other languages, documentation, etc.

**Comment by jameswomack** [comment]
That makes sense—thank you
