### ISSUE TITLE
Low severity vulnerability found on merge-options@0.0.64

### ISSUE THREAD

**Issue by ceastman-ibm** [dylang/npm-check#288]
snyk test npm-check

Testing npm-check...
✗ Low severity vulnerability found on merge-options@0.0.64
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:merge-options:20180415
- from: npm-check@5.7.0 > merge-options@0.0.64
Upgrade direct dependency merge-options@0.0.64 to merge-options@1.0.1

**Comment by LinusU** [comment]
Fixed in v5.7.1
