### ISSUE TITLE
Can I use npm-check with bower?

### ISSUE THREAD

**Issue by andreicristianpetcu** [dylang/npm-check#29]
Hello, 

Can I use npm-check with bower?

I really like npm-check and I use it for my backend dependencies, but I would like to use it for the frontend stuff. I really like the -u option since I can upgrade only the minor stuff for security and stability :P

Thank you for building this package!

**Comment by dylang** [comment]
Sorry, I'm not planning on supporting bower.

**Comment by andreicristianpetcu** [comment]
I have seen that npm is planning to add front-end dependencies soon.

**Comment by dylang** [comment]
Actually npm supports front-end dependencies today.  :smile: 

This is why I don't use bower any more.
