### ISSUE TITLE
pnpm integration

### ISSUE THREAD

**Issue by matt3224** [dylang/npm-check#291]
Hi, I have setup pnpm which is working well and I have followed the docs to add the env var to my bash_profile, yet it seems when i run npm-check i get a package-lock.json file still and will later get warnings from pnpm that say that packages were installed by another package manager.

I have mentioned this to the pnpm maintainer, but thought it was worthwhile asking here too in-case anyone was aware of this or had any thoughts.

Thanks!

**Comment by zkochan** [comment]
I suggest using [preferred-pm](https://github.com/zkochan/preferred-pm). It can detect what package manager was used with the project. So `npm-check` will be able to automatically select the most preferred package manager for a given project
