### ISSUE TITLE
Show unused dependencies with interactive (-u) option?

### ISSUE THREAD

**Issue by trevordmiller** [dylang/npm-check#295]
I really like using the interactive `-u` option (ie `npx npm-check -u`) but wish it showed unused packages like the non-interactive `npm-check` option does. Could the interactive option also show unused packages that can be uninstalled when you check them?

**Comment by LinusU** [comment]
I like it 👍

**Comment by mattietea** [comment]
I wanted this too! In the meantime, I wrote a bash function you can use if anyone is interested. This was my first time writing one so forgive me for any errors (feel free to leave suggestions if there are errors)! It's probably super overkill but I used it as a chance to learn how to write bash scripts. I renamed the call from `npm-check` to `ncu` but of course feel free to change it. Anyways, this is how it works: 

`ncu <options>` - Will run `npm-check -u <options>; npm-check <options>`. Runs the interactive check in the current working directory then the normal check to show the unused dependencies.  

`ncu -g <options>` - Will run `npm-check -g -u <options>`.

`ncu <path> <options>` - Will run `npm-check ~/some/file/path <options>`.
- Note: I couldn't get it to work with the -u option but the documentation doesn't specify that this should work either so I think it's ok. 

```bash
function ncu() {
  case $1 in
    "-g") 
      npm-check $@ -u 
      ;;
    /* | .*)
      npm-check $@
      ;;
    *)
      npm-check $@ -u
      npm-check $@
      ;;
  esac
}
```

**Comment by trevordmiller** [comment]
Possibly related: it would be nice to show dependencies that have deprecated in the `-u` list as well.

**Comment by trevordmiller** [comment]
Perhaps a tool like `depcheck` could be used for the implementation under the hood. Or whatever the non `-u` interactive version is currently using, having the interactive version match with things like:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/5497885/74983418-346df080-53f3-11ea-8941-12a1b2e88902.png">
