### ISSUE TITLE
Look in all files in /bin for unused packages

### ISSUE THREAD

**Issue by dylang** [dylang/npm-check#32]
Today we are only looking at `*.js` files. This change is to look at all files in `/bin` because people like to not have extensions there.

Follow up to #19.

**Comment by mrkev** [comment]
+1

**Comment by martinheidegger** [comment]
:+1:

**Comment by dylang** [comment]
Sorry, this can't be done without changes to [depcheck-es6](https://github.com/lijunle/depcheck-es6). If people want this, please request or make a pull request for the feature there.

One of the complexities is that `depcheck-es6` needs to know what type of code to parse (`js`, `es6`, `jsx`, `coffeescript`, etc.) 

A way around this problem is very simple: **always give your files extensions, even in the `/bin` directory.** This makes it possible for tools like this one to parse, as well as IDEs, etc. 

The name users use on the command line and via `npm run` *does not need to have the extension*. You can see this in `npm-check` today:

```json
  "bin": {
    "npm-check": "bin/cli.js"
  },
```

https://github.com/dylang/npm-check/blob/master/package.json#L20-L22
