### ISSUE TITLE
How to set up the default download tool? Replace npm with cnpm.

### ISSUE THREAD

**Issue by zhe-he** [dylang/npm-check#325]
Hope to add an attribute, or tell me where I can change it. Thank you.

**Comment by zhe-he** [comment]
Solved.
`NPM_CHECK_INSTALLER=cnpm npm-check -u`

**Comment by von7750** [comment]
![image](https://user-images.githubusercontent.com/19551623/65307755-15a4cd00-dbbb-11e9-90fd-71d23e100d04.png)
in windows  it works
