### ISSUE TITLE
Problem with npm updating

### ISSUE THREAD

**Issue by hypnocolor** [dylang/npm-check#33]
Hi!
When I try to check latest updates of my packages, npm-check offers me to update npm:

$ npm-check -u -g
? Choose which packages to update. (Press <space> to select)

 Minor Update New backwards-compatible features.
❯◯ npm  2.11.3  ❯  2.14.2  https://docs.npmjs.com/

But I have already updated npm 2.14.2 through npm-check!
I tried to re-install npm-check and npm separately but problem is still present. If it will help, I use OS X 10.10.5.
Probably my English is not so good as I wanted it to be, sorry for this :)

**Comment by hypnocolor** [comment]
Here is a debug output:

$ npm-check -u -g --debug
{ npm:
   { moduleName: 'npm',
     homepage: 'https://docs.npmjs.com/',
     error: undefined,
     latest: '2.14.2',
     installed: '2.11.3',
     isInstalled: true,
     notInstalled: false,
     packageWanted: '2.11.3',
     packageJson: '2.11.3',
     isPrivate: undefined,
     devDependency: false,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '2.11.3',
     semverValid: '2.11.3',
     easyUpgrade: false,
     bump: 'minor',
     unused: undefined } }

**Comment by hypnocolor** [comment]
Could you please answer me something about this? The problem is still actual :\

**Comment by hypnocolor** [comment]
Could you please answer me something about this? The problem is still actual :\

**Comment by dylang** [comment]
Can you provide the output of `npm config get prefix`,  `which npm`, `node --version`, and `which node`. Thanks!

**Comment by hypnocolor** [comment]
Sure!
```
> $ npm config get prefix
/Users/hypnocolor/.node

> $ which npm
/Users/hypnocolor/.node/bin/npm

> $ node --version
v0.12.7

> $ which node
/usr/local/bin/node
```

**Comment by dylang** [comment]
Can you provide:

`which npm-check`

`ls -al /Users/hypnocolor/.node/bin/npm`

Thanks!

**Comment by hypnocolor** [comment]
```
> $ which npm-check
/Users/hypnocolor/.node/bin/npm-check

> $ ls -al /Users/hypnocolor/.node/bin/npm
lrwxr-xr-x  1 hypnocolor  staff  38 Sep 13 20:44 /Users/hypnocolor/.node/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

**Comment by dylang** [comment]
I'm sorry @hypnocolor, I'm out of ideas and I don't have time to add more debugging code right now.

npm 3 is out now, and I released a new version of npm-check. Try both of those and see if they help. I'm going to close this ticket but you can keep adding comments if you figure anything else out.
