### ISSUE TITLE
scoped modules marked as unused

### ISSUE THREAD

**Issue by MarkHerhold** [dylang/npm-check#35]
Scoped packages, that are npm installed in `package.json` and required() are marked as not used when running `npm-check`.

For example: add `"@jigsaw/ansi-canvas": "0.1.0"` to package.json and require it somewhere. Running `npm-check` reports that it is not used.

```
@jigsaw/ansi-canvas 😕  NOTUSED?  Possibly never referenced in the code.
```

**Comment by dylang** [comment]
Thanks @MarkHerhold! 

This is handled by [depcheck](https://github.com/rumpl/depcheck). We'll need to update how it finds modules to fix this.

**Comment by MarkHerhold** [comment]
@dylang thanks for clarifying where this logic was!

It looks like there is already an issue open on depcheck for this: https://github.com/rumpl/depcheck/issues/32

**Comment by dylang** [comment]
Scoped module support is now included! Upgrade to `npm-check@4.1.0` and tell me how it goes!

**Comment by MarkHerhold** [comment]
@dylang Sorry, I may be doing something wrong, but it does not appear to be working.

Tested using `@websdk/nap` this time (another random package) and required it in one of the project files.
```
    "@websdk/nap": "^0.9.5",
```
```
var nap = require('@websdk/nap');
```
I am running the latest version:
```
npm-check --version
4.1.0
```

I looked at `depcheck-es6` briefly and didn't see anything about scoped package support, but I could have easily missed it.

**Comment by dylang** [comment]
Thanks for testing it, do you want to make a PR to `depcheck-es6`?

**Comment by MarkHerhold** [comment]
@dylang I would like to, but doing that is not an easy thing for me to do. I need to get approvals from management, which is not easy and will probably take a long time even if I am successful. :disappointed:

**Comment by dylang** [comment]
@MarkHerhold I'm sorry to hear there's bureaucracy to participate in open source projects where you work. That must be frustrating. I appreciate that you are able to create issues and provide feedback without an approval process. Have you made a ticket for `depcheck-es`? Maybe that author or another user will be able to provide a fix.

**Comment by dylang** [comment]
Based on #45 there might be a deeper scoped project issue in my code. I should finally get around to adding tests to the code asap.
