### ISSUE TITLE
Where does npm-check get the link from?

### ISSUE THREAD

**Issue by Svish** [dylang/npm-check#363]
Re "Provides a link to the package's documentation so you can decide if you want the update", where does `npm-check` get that link from?

I ask because I just noticed one of my packages shows the URL `http://ssh.dev.azure.com/v3/myorganization`, which is not right. The package does have a `repository/url` in its `package.json` of `git@ssh.dev.azure.com:v3/myorganization/Project/my-package`, which at least contains some of the parts, so maybe there's some parsing/magic happening from that, but other than that, there's no URL provided in the package.

Would be helpful to know for newb package authors like myself. 🤔

**Comment by Artoria2e5** [comment]
The logic is in https://github.com/dylang/npm-check/blob/master/lib/in/best-guess-homepage.js. The git-to-http conversion happens at the external library https://github.com/repo-utils/giturl/blob/master/lib/giturl.js. You should probably add an explicit homepage or bugs URL instead.

I mean, the whole git-to-http-url mapping is never possible to do "right": you can't deduce the type of web git interface the server is offering [or not offering at all!] only from the git url. You can try giving them a new rule for azure-looking sites, but then there's cgit and all kinds of other weird stuff.

**Comment by Svish** [comment]
That's pretty much what I was looking for, thank you! Defining `homepage` seems to be the most stable solution in my case then. 👍

And yeah, although I guess for example Azure DevOps and BitBucket could be looked at as mainstream and common enough to add support for, it will probably just end up in a never ending rabbit-hole of weirdness.
