### ISSUE TITLE
Registry errors

### ISSUE THREAD

**Issue by oliversalzburg** [dylang/npm-check#37]
I'm seeing a lot of errors like `Registry error Request to https://registry.npmjs.org/jshint-stylish/ failed` when running `npm-check`.

The modules for which the request fails change every time I run `npm-check`.

**Comment by dylang** [comment]
Interesting, sorry this is happening for you.  

Can you give me more details?

* Has this always been happening?
* Is it happening today?
* Does it happen with other projects?
* Can you share your `package.json`?
* How's your internet connection? Can you share the output for https://www.npmjs.com/package/speed-test

In the future I'll try to provide more details with the registry errors. I've never seen them before so I didn't think it would be necessary.

**Comment by oliversalzburg** [comment]
Hi @dylang, thanks for your quick reply.

> Has this always been happening?
On my work desktop, yes. It seemed to be working just fine at home last night.

> Is it happening today?
Yes, I just reproduced it.

> Does it happen with other projects?
I just tried to reproduce it with 4 other projects and was not able to.

> Can you share your `package.json`?
I've sent you a copy to the email address listed on your GitHub profile.

> How's your internet connection?
```
      Ping  49 ms
  Download  65.3 Mbps
    Upload  12.2 Mbps
```

I'm on x64 Windows 7 with Node 4.0.0 in case that has any relevance.

**Comment by dylang** [comment]
I ran it with your `package.json` and using Node 4.0.0 and had no issues. There was just one package it couldn't get a version for, and it looks like it's a privately scoped one. 

I don't have a Windows VM to try this on, but the network code is pretty generic, just `http` requests using common modules. 

> On my work desktop, yes. It seemed to be working just fine at home last night.

Could it be an issue with your network at work? 

Do you have co-workers that could try it? I'm especially curious if it is only happening on Windows. 

Have you tried other versions of Node?

**Does anyone else have this issue? I could use a hand to get something I can repro locally.**

**Comment by oliversalzburg** [comment]
Just FYI, the complete error is:
```
{ [GotError: Request to https://registry.npmjs.org/chai/ failed]
  nested:
   { [Error: connect ETIMEDOUT 185.31.17.162:443]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '185.31.17.162',
     port: 443 },
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '185.31.17.162',
  port: 443 }
```
I'll see if I can find out anything else.

**Comment by oliversalzburg** [comment]
Co-worker has the same issue. He's on Windows 8.1 as well. I'll check OSX later as well.

**Comment by oliversalzburg** [comment]
Seems to work fine on OSX. I'm on Windows 10 at home. So either this is specific to our network in combination with Windows, or it's something with Windows 8, I guess :\

**Comment by dylang** [comment]
`185.31.17.162` is not the ip address I get for `registry.npmjs.org`. Maybe that's some kind of proxy or load balancer which is not as reliable as the npm registry everyone else is using?

```
 nslookup registry.npmjs.org
Server:		10.1.10.10
Address:	10.1.10.10#53

Non-authoritative answer:
registry.npmjs.org	canonical name = a.sni.fastly.net.
Name:	a.sni.fastly.net
Address: 199.27.76.162
```

**Comment by dylang** [comment]
I'm going to close this as it does not seem related to `npm-check`, but if you find a solution or reason why this happening I'd love to know.

**Comment by oupala** [comment]
I have the same problem, with the same ip address. See #144.
