### ISSUE TITLE
audit warnings because of a dependency on an outdated `mem`

### ISSUE THREAD

**Issue by jandockx** [dylang/npm-check#376]
Getting audit warnings because of a dependency on an outdated `mem`, via an outdated `deppcheck`.

Kinda ironic, isn't it?

![image](https://user-images.githubusercontent.com/3955483/72205959-09ee5680-3489-11ea-9ec2-648a8285112b.png)

**Comment by kabarakh** [comment]
Fixed it in #378 - worked in our tool we use npm-check for ;)

**Comment by jandockx** [comment]
@kabarakh Great! Now it's up to Dylan … ;-)

**Comment by jandockx** [comment]
fixed in the 5.9 series
