### ISSUE TITLE
is this repo abandoned?

### ISSUE THREAD

**Issue by andrei9669** [dylang/npm-check#395]
it seems like there has been no development for 9 months.
I really prefer this to npm-check-updates

**Comment by MarkVaughn** [comment]
ping @LinusU for status

**Comment by MatthewS2077** [comment]
Interactive mode (npm-check -u) is brilliant. 👏

It's never been easier to understand the currency of my package.json(s), and keep up to date. 👍

**Comment by andrei9669** [comment]
I mean, this package is perfect as it is but it is missing one crucial thing. if a package has a locked version, it should display it differently in npm-check -u view.

**Comment by dl748** [comment]
Well that and its using deprecated packages.  I wish it would get at least security updates.

**Comment by uran1980** [comment]
ping @LinusU for status

**Comment by LinusU** [comment]
I'm using this quite often and I haven't ran into any troubles or missing features, thus I haven't committed anything recently...

So, it's not abandoned ☺️
