### ISSUE TITLE
Suppress color output

### ISSUE THREAD

**Issue by mike-ward** [dylang/npm-check#43]
Could we have an option to suppress color output? I find it difficult to read the color output.

**Comment by dylang** [comment]
Hi @mike-ward 

```
npm-check --color=false
```

Can you share a screenshot with color? It's impossible to choose colors that work well for *everyone*, but I can try to at least not make it unusable.

**Comment by mike-ward** [comment]
It's mostly the dark blue I can't see. Dark red on black is also difficult for me to see. The other colors work well.

![image](https://cloud.githubusercontent.com/assets/567927/10026850/f11bf81c-6131-11e5-8cd9-bbd659756dac.png)
