### ISSUE TITLE
Success message even if package.json is missing or invalid

### ISSUE THREAD

**Issue by samuelmartineau** [dylang/npm-check#44]
If the **package.json** isn't well formed I get a success message. Do you think that it would be nice to check if the json is good?

FYI in my test I have just removed a comma.

**Comment by dylang** [comment]
Thanks! Updated the title so it makes more sense for me when I have time to look into this.

**Comment by samuelmartineau** [comment]
Yeah sorry for the title, it's because I like your success message :blush:

**Comment by js08** [comment]
@dylang @samuelmartineau did you guys fix it

**Comment by dylang** [comment]
@js08 No this is not fixed yet, that's why this issue is still open. Do you want to create a pull request?
