### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mateatslc** [dylang/npm-check#49]
`npm i -g npm-check`
leaves me with
`npm WARN install Couldn't install optional dependency: shasum check failed for /tmp/npm-8548-7875fd00/registry.npmjs.org/depcheck-es6/-/depcheck-es6-0.5.4.tgz
npm WARN install Expected: 7cfa907d49a6db295acfd0da89b326d9e8a5a071
npm WARN install Actual:   a4e35e665e4d13d749edddeb1419dd4621175c4a
npm WARN install From:     https://registry.npmjs.org/depcheck-es6/-/depcheck-es6-0.5.4.tgz`

my node version is 4.1.1, npm is 3.3.6
`npm cache clean` didn't help either

**Comment by aenciso** [comment]
Same here

**Comment by dylang** [comment]
I'm seeing the problem as well.

**Comment by dylang** [comment]
I've reported https://github.com/lijunle/depcheck-es6/issues/79

**Comment by prayerslayer** [comment]
Same here with npm 3.3.6, nvm 0.29, node 0.12.7, MacOS 10.10.5.

**Comment by dylang** [comment]
I published a new version of `npm-check` with the version of `depcheck-es6` hardcoded to an older release.

**Comment by mateatslc** [comment]
verified, works, awesome turnaround time. thanks, @dylang! :metal:

**Comment by lijunle** [comment]
Sorry, I am looking into it.

**Comment by lijunle** [comment]
I published a new version 0.5.5 with the same content. @dylang could you please handle your package change. 

I am sorry about blocking your work.
