### ISSUE TITLE
Respect package.json update policy for packages 

### ISSUE THREAD

**Issue by okonet** [dylang/npm-check#50]
In my `package.json` I'm using pinned versions. It would be cool to keep it that away after doing updates.

I would even expect that it can be set per-package. So if one package uses `~` or `^` or exact version (installed with `--save-exact`) it should not be altered in the resulting `package.json`

**Comment by dylang** [comment]
Great idea.

Would you want me to follow your `npmrc` settings, or just use whatever it was before?

```bash
# set your default to tilde
npm config set save-prefix='~' 

# remove the auto-prefixing
npm config set save-prefix=''
```

Anyone else have opinions about this? I'm not sure if this a major change or a bug fix.

**Comment by okonet** [comment]
Hmm, not sure. I think `npmrc` would be enough. It can get tricky with complex ranges I guess.

**Comment by okonet** [comment]
If it will work with project-based `.npmrc` I'm totally fine with it! :)

**Comment by dylang** [comment]
+ `--save-exact` support to force no `^`.

**Comment by rstacruz** [comment]
i'd be happy with a simple `npm-check -u --exact` flag.

**Comment by mik01aj** [comment]
+1 for both `.npmrc` support and the `--exact` flag. :+1:

**Comment by kburson** [comment]
+1 from me for both .npmrc support and the --exact flag. :+1:

**Comment by glen-84** [comment]
+1 ... changes my exact version to `^`, which is unfortunate.

**Comment by dylang** [comment]
There is now a `--save-exact` feature, thanks to @pgilad https://github.com/dylang/npm-check/pull/91

`npm i -g npm-check` to get version 5 which has this feature.
