### ISSUE TITLE
Doesn't show outdated global repositories when -g is used

### ISSUE THREAD

**Issue by aminnaggar** [dylang/npm-check#53]
For some reason it doesn't seem to be able to list global outdated packages.

![npm_check](https://cloud.githubusercontent.com/assets/857186/10615436/cd34523e-772d-11e5-835b-41d365727778.jpg)

Anything I'm doing wrong?

**Comment by dylang** [comment]
Interesting issue. Can you share some information:

```
npm config get prefix
```

```
which npm-check
```

```
npm-check --version
```

```
npm-check -g --debug
```

That last one will be long, you can do 

```
npm-check -g --debug | pbcopy
```

to put it in your clipboard and then paste it here.

**Comment by vvMINOvv** [comment]
Thanks @dylang , the last one wasn't so bad actually here it all is

![screen](https://cloud.githubusercontent.com/assets/857186/10676776/8352fe0e-78d6-11e5-815b-6a4c1c13b4bc.jpg)

**Comment by dylang** [comment]
It looks like you installed node via Brew which might be the cause of this problem. I recommend installing node using [nvm](https://github.com/creationix/nvm).

If you look at the output of `which npm-check` and the `path` in `npm-check --debug`, they are not the same, but they should be.

I get the path using [global-prefix](https://www.npmjs.com/package/global-prefix). You should check out his code, see if it exhibits the same problem, and report an issue there.

**Comment by valentinvieriu** [comment]
I had the same problem. Also had node installed via bower. If you put this line in your .bashrc file will work
`export PREFIX="/usr/local/"`

or you can try to run this directly 
`PREFIX="/usr/local/" npm-check -g -u`

**Comment by dylang** [comment]
Thanks for the workaround @valentinvieriu! 

@valentinvieriu  and @vvMINOvv Can you try https://github.com/eush77/npm-prefix to see if it provides the correct directory without the workaround? If it works, I'll switch to that library!

**Comment by vvMINOvv** [comment]
@valentinvieriu nice find buddy

@dylang I'll give it a spin tonight and let you know

**Comment by valentinvieriu** [comment]
@dylang npm-prefix fails. The basic example( posted on the website) throws an exceprtion
```
/Users/xxxx/node_modules/untildify/index.js:7
		throw new TypeError('Expected a string');
		^

TypeError: Expected a string
    at module.exports (/Users/xxxx/node_modules/untildify/index.js:7:9)
    at module.exports (/Users/xxxx/node_modules/npm-prefix/index.js:10:10)
    at Object.<anonymous> (/Users/xxxx/app.js:3:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by dylang** [comment]
Interesting @valentinvieriu, do you want to create a bug for `npm-prefix`?

**Comment by dylang** [comment]
I've switch modules to find the location of the global modules.

`npm -g i npm-check` to get the latest version and see if it fixes the problem.

#87 is still open if it's not fixed.

**Comment by mgcnrx11** [comment]
@dylang in my case, npm-prefix report the wrong path.
i installed node by homebrew and it should be /usr/local, but npm-prefix showed /usr/local/Cellar/node5/5.11.1

**Comment by max-devjs** [comment]
Happened a couple times. Example, last time npm-check found all the outdated packages but one (output after updating):

```
$ npm-check -u -g
❤️  Your modules look amazing. Keep up the great work. ❤️

$ npm outdated -g
Package    Current  Wanted  Latest  Location
changelog    1.2.1     git     git
```
npm-check did not complains about it but, if I am not wrong, that `git` is (one of?) the cause(s) (output with a new update available):

```
$ npm outdated -g
Package    Current   Wanted   Latest  Location
changelog    1.2.1      git      git
citgm      1.11.13  1.11.13  1.11.14

$ npm-check -u -g

citgm   😎  PATCH UP  Patch update available.
                     npm install --global citgm@1.11.14 to go from 1.11.13 to 1.11.14
```

Node installed with [nvm](https://github.com/creationix/nvm)

```
Ubuntu 16.04.2 64
node -v: v7.6.0
npm -v: 4.6.1
nvm --version: 0.33.2 and 0.32.1
```

```
npm config get prefix: ~/.nvm/versions/node/v7.6.0
which npm-check: ~/.nvm/versions/node/v7.6.0/bin/npm-check
npm-check --version: 5.4.4
npm-check -g --debug: currently there is no path output
```
