### ISSUE TITLE
Scoped packages in different registries requiring authentication

### ISSUE THREAD

**Issue by moll** [dylang/npm-check#57]
Hey,

When you've got a few scoped packages in different registries with authentication requirements, npm-check throws "Registry error Basic authentication must be done with auth option".

Cheers

**Comment by dylang** [comment]
Are you expecting `npm-check` to know which registries to use for each package? It's not going to do that. I didn't think `npm` could do that.

**Comment by moll** [comment]
Hey again! Long time no talk. :)

Fortunately NPM does support scoped packages in different registries based on its .npmrc. Otherwise I wouldn't use the feature, too.

See:
```
npm config set @myco:registry http://localhost:4873
```

Cheers

**Comment by dylang** [comment]
That's cool! I didn't realize that. Thanks for sharing!

**Comment by dylang** [comment]
Hi @moll - can you check your registry config and see if it ends with a `/`? If it does not, can you add one and see if this fixes the problem?

For example:
* before: `http://localhost:4873`
* after: `http://localhost:4873/`

I've created an issue for this that you can follow or help create a PR: https://github.com/sindresorhus/package-json/issues/25

**Comment by dylang** [comment]
I'm going to close this as there's now a PR to fix this (https://github.com/sindresorhus/package-json/pull/26) and a workaround - add the `/` to the end of the registry setting.

Let me know if these fixes don't work for you.

**Comment by moll** [comment]
Okie, thanks! I'll report back once I try npm-check again.
