### ISSUE TITLE
Install required packages

### ISSUE THREAD

**Issue by jlgrall** [dylang/npm-check#6]
Could you please also tell when a package is required in the code but not yet installed ? It would make it easier to make quick prototypes: just write the require in the code, then let npm-check install all required packages.

It should not be too hard: you already know which require() are in the code, and you already know which packages are installed.

What do you think ?

**Comment by dylang** [comment]
great idea! this could mean a change to the [depcheck](https://github.com/rumpl/depcheck) module I'm using, or a new module. Do you want to find a good module that does this - or create a PR for `depcheck`?

**Comment by dylang** [comment]
This is a cool idea, but I'm not sure how to implement it efficiently. If you find a way, let me know!
