### ISSUE TITLE
Deprecate version 0.12 support.

### ISSUE THREAD

**Issue by lijunle** [dylang/npm-check#62]
Hi, @dylang 

I am considering deprecate version 0.x and io.js support in depcheck. Node.js v4 and v5 are awesome, and everybody should upgrade to it.

Do you have any concerns to [support it](https://github.com/dylang/npm-check/blob/master/.travis.yml#L6)?

**Comment by dylang** [comment]
It's not that easy for companies to upgrade. My company is still in the process of moving from 0.11 (yes, I know), to v4, and i know of companies in the area still using 0.10. 

Babel, polyfills, and Travis seem to make cross-version support pretty painless - are there reasons you want to stop supporting older versions?

**Comment by lijunle** [comment]
Hmm... In such case, it could better to keep support it.

The cause of my idea is babel@6 with babel-runtime@5.8.34 is [broken](https://ci.appveyor.com/project/lijunle/depcheck/build/20/job/h46lo90c6eqjplkn) on Windows with node version 0.10. Instead of trying to fix it, I consider to deprecate it.

Anyway, I will assert the support back in depcheck.

**Comment by lijunle** [comment]
Finally, I decided to remove 0.10 support as [what you did](https://github.com/dylang/npm-check/commit/8e173955c40d308862167f7f825f65144eeb3b12). Thanks!
