### ISSUE TITLE
npm-check -u fails on Windows

### ISSUE THREAD

**Issue by alexmcmillan** [dylang/npm-check#64]
Windows 10
NodeJS 4.2.2
npm 2.14.7
npm-check 4.1.3

I have `babel-core v5.8.25` installed in the current repository as a devDependency.

1) Executing `npm-check -u` prompts me with your (very nice) interactive update interface, offering a major update of babel-core, `v6.2.1`.
2) I press `space` to select the babel-core update and a `X` appears, then `enter` to proceed with the update.
3) I see messages logged to the console from scripts I have which run automatically on creation of a new console
4) I see the babel-core npm tree and your `[npm-check] Update complete!` / re-test message.
5) `npm ls --depth=0` shows babel-core still at v5.8.25
6) I change into the directory that fresh consoles default to and see a `node_modules` directory with `babel v6.2.1` inside.

I believe your method of executing the `npm update` command is creating a new instance of `cmd.exe` and running any automated scripts, then installing into whatever *current* (default) directory the new console opens to (which, in Windows, is unlikely to be the same directory `npm-check -u` was executed from).

**Comment by dylang** [comment]
I think I have fixed this.

Can you upgrade to the latest version (5.x) and try again?

**Comment by alexmcmillan** [comment]
Brilliant - thank you very much :+1:
