### ISSUE TITLE
not working on node v10: Promise is not defined

### ISSUE THREAD

**Issue by vitalets** [dylang/npm-check#66]
hi, after install and run npm-check got this:
```js
.../node_modules/npm-check/node_modules/depcheck/dist/index.js:192
  return new Promise(function (resolve) {
             ^
ReferenceError: Promise is not defined
```
node version is `v0.10.38`
It seems native promise support was added only in node 12 http://stackoverflow.com/a/24371533/740245

Maybe add `engine` field to package.json or use some promise lib?

**Comment by lijunle** [comment]
This is related to depcheck.

Any reason to stick on 0.10.x? Depcheck has deprecated the 0.10.x support.

**Comment by vitalets** [comment]
> Any reason to stick on 0.10.x? Depcheck has deprecated the 0.10.x support.
yes I will update node. It would be convenient to have a notice about node version it readme

**Comment by lijunle** [comment]
@vitalets @dylang I have specify the node engine version in depcheck package.json and mention it in depcheck README. I think it could be OK to close this issue.
