### ISSUE TITLE
Add option to don't display emojis?

### ISSUE THREAD

**Issue by edravis** [dylang/npm-check#68]
Is this on the roadmap?

Why:
1. Most of the Linux distros don't support them well by default
2. Most of the ssh gateways don't support them at all; e.g: continuous integration/deployment
3. We cannot catch the output for other issues without parsing first
4. That's imho: are annoying

I can do the PR if you think is an interesting feature.

Good job with the module, btw. Really nice the interactive shell.

**Comment by dylang** [comment]
Great idea, I'd be happy to accept a PR for this.

1. Interesting, I did not know this.
2. Makes sense given the first point.
3. I'd like to make this easier (see #36).
4. I've gotten positive feedback, but I agree. It was my attempt to help the module "stand out".

**Comment by LinusU** [comment]
I for one think the emojis is awesome and what gives this module its soul :raised_hands: 

Maybe it's a better idea to have a flag for more "parseable output", there are a few other unix tools that does this...

**Comment by dylang** [comment]
Great idea, I'm going to add a flag to disable emoji. I hoped to do it automatically but I haven't figured out how. I created [a module-request for supports-emoji](https://github.com/sindresorhus/module-requests/issues/64) if anyone is interested in a challege!

**Comment by dylang** [comment]
@edravis - with this option, do you think it would be ok to use characters that work instead of emoji, or no characters at all?

For example:

* characters from [figures](https://github.com/sindresorhus/figures/blob/master/index.js) `♥ Your modules look amazing. Keep up the great work. ♥`

or

* just text `Your modules look amazing. Keep up the great work.`

**Comment by dylang** [comment]
I've decided for the `--no-emoji` option to just not show any symbols.

**Comment by edravis** [comment]
I <3 you

**Comment by dylang** [comment]
@edravis haha! I showed my wife, she laughed and wasn't jealous. :)
