### ISSUE TITLE
Report dependencies being used but not in the package.json

### ISSUE THREAD

**Issue by inikulin** [dylang/npm-check#69]
Thank you for the great project. It would be really great if it'll support missing deps check, like `--missing` option in [dependency-check](https://www.npmjs.com/package/dependency-check).

**Comment by lijunle** [comment]
Related: https://github.com/depcheck/depcheck/issues/41

**Comment by lijunle** [comment]
@dylang A new version 0.6.0 of depcheck is published and contains this feature. You might want to upgrade and leverage it in npm-check.

**Comment by lijunle** [comment]
@dylang 

I want to point out, your current [implementation](https://github.com/dylang/npm-check/blob/e144741846e57342a5f505984259f7fdd37b7551/lib/check-npm.js#L18) to check if the folder exist under node_modules is not right. 

With npm@3, the dependencies by dependencies will be flatten to the first level folder. The folder exists in node_modules does not mean the package is declared in package.json.

My suggestion is to use the return value from depcheck `result.missing`.

**Comment by dylang** [comment]
Thanks for this helpful information @lijunle!
