### ISSUE TITLE
NPM upgrade issues

### ISSUE THREAD

**Issue by jacobrillema** [dylang/npm-check#70]
So running Windows 10 x64 with NodeJS installed via Chocolatey in Program Files and with NPM installed globally I run into issues upgrading NPM. If i do a "which npm" it returns c:\users\jacob\appdata\roaming\npm\npm.cmd" and "which node" it returns "c:\program file\nodejs\node.exe". Running npm-check -u -g it finds that I do have an outdated NPM version at 3.3.12 and I can confirm that running npm --version. I select the minor upgrade path to 3.5.2 and from the output everything looks to install find. When I run npm --version it shows it was upgraded to 3.5.2 correctly. Now if I re-run npm-check -u -g it detects the that NPM needs to be upgraded again. I am not sure how it is detecting that but since a couple months ago I have been having this program with just NPM specifically. I can't determine where it is finding that previous version?

**Comment by dylang** [comment]
This may be related to #64. 

Can you upgrade to the latest version (5.x) and try again?

**Comment by jacobrillema** [comment]
So i just tried installing latest npm check using PowerShell on Windows 10 x64. (npm install -g npm-check). When I run this in PowerShell (npm-check -u -g) I get the following error.

C:\ProgramData\npm\node_modules\npm-check\lib\cli.js:4
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by dylang** [comment]
Node 0.12 isn't currently supported. Are you able to upgrade to the latest stable version, node 4?

If you are not able to upgrade node to 4 or 5, this PR will add support for node 0.12: #120

Want to give it a try and us know if it works for you?
