### ISSUE TITLE
Ignore modules

### ISSUE THREAD

**Issue by vjpr** [dylang/npm-check#71]
Allow ignoring certain packages that you don't want to update for now.

**Comment by dylang** [comment]
cool idea, how would you want to do that?

**Comment by vjpr** [comment]
**package.json**

```
{
  "npm-check": {
    "ignore": ["async", "underscore"]
  }
}
```

**Comment by wprl** [comment]
I just came here to open the same issue :)  I like the suggested solution with a `package.json` config value.

**Comment by vjpr** [comment]
In interactive mode the ignored packages would simply display in their own section.

**Comment by rstacruz** [comment]
great. here are some packages i would ignore:

- babel's packages (like [babel-preset-stage-0](https://www.npmjs.com/package/babel-preset-stage-0))
- css-only packages (like [iconfonts](https://www.npmjs.com/package/iconfonts) or [normalize.css](https://www.npmjs.com/package/normalize.css))

**Comment by wprl** [comment]
Pre-git

**Comment by lukewaite** [comment]
@dylang Are you open to PRs implementing what has been discussed above?

**Comment by dylang** [comment]
Hi @lukewaite, I am!

**Comment by dylang** [comment]
I was thinking about a `--ignore <glob>` feature, like 

```
$ npm-check --ignore babel-* --ignore iconfonts --ignore normalize.css
```

How does that sound?

**Comment by eldino** [comment]
Functionality added in PR #142

**Comment by jperasmus** [comment]
I have a similar issue, which I thought this might have solved, but doesn't seem to work with the `--ignore` parameters. We use webpack to alias certain local utilities, for instance:

```
aliases: {
  ...
  permissions: '../some-path-to-utils/permissions.js',
  ...
}
``` 

and then we simply import the aliased modules into our JS code like:

```
import Permissions from 'permissions';
```

This `npm-check` tool now picks up these aliased modules and mark them as missing.

Is there any existing functionality that I can use to ignore these aliased modules so they don't get marked as missing?

**Comment by amilajack** [comment]
This was merged today. Waiting for npm permissions so I can publish this.
