### ISSUE TITLE
"babel-plugin-transform-runtime" dependent non-display "babel-runtime" (exceptions)

### ISSUE THREAD

**Issue by LiaoSept** [dylang/npm-check#78]
when introducing "babel-plugin-transform-runtime" need to be given "babel-runtime" exception

see https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js
see https://www.npmjs.com/package/babel-plugin-transform-runtime

**Comment by dylang** [comment]
Hi @LiaoSept, thanks for taking your time to create this issue. 

I'm not sure what the problem is. Can you describe the problem, or provide a screenshot and instructions or code so I can try to reproduce the problem?

**Comment by LiaoSept** [comment]
see https://gist.github.com/LiaoSept/ed1768df1f81e855e930#file-readme-md

**Comment by LiaoSept** [comment]
@dylang

**Comment by lijunle** [comment]
@LiaoSept could you please send a screenshot about the exception?
