### ISSUE TITLE
Check versions in package json against actual node_modules

### ISSUE THREAD

**Issue by vitalets** [dylang/npm-check#79]
hi!
Could you add an option to check this:
http://stackoverflow.com/questions/35061525/check-versions-in-package-json-against-actual-node-modules

thanks!

**Comment by dylang** [comment]
Great idea. Are you interested in making a PR for this?

**Comment by vitalets** [comment]
Ok, I will try to find time for that.
Could you just point from architecture side what modules should I change / create?
Will we put it under option or just show somehow in current interface?

**Comment by dylang** [comment]
I think a new command-line option and a new javascript file would be ideal. I recommend building it without using the update interface first, maybe just print an error with a list of node modules that don't match the package.json versions, and exit the program with `-1`. 

If you want to propose how you would like to implement this before writing code I'm happy to discuss your ideas.

**Comment by eyalw** [comment]
+1

**Comment by eyalw** [comment]
adding my text from a different issue, reasoning this feature:

> - I work with a team, they upgrade modules and install new ones. 
> - Then I git-pull, run my code, and it breaks.
> -- if it's easy, the error will say I'm missing a module
> -- if it's not, a dependency version has been bumped up and my code will break and no indicative warning will show up.
> 
> How about adding an option to run npm-check programmatically at the start of my code and have it make sure node_modules match package.json?

**Comment by eyalw** [comment]
Code that performs some of the wanted feature:

```javascript
var npm = require('npm');
require('console.table');

console.log('Checking npm dependencies…');
npm.load(function(err, loadedNpm) {
  if (err) throw err;

  loadedNpm.commands.outdated([], true, function(err2, dependencies) {
    if (err2) throw err2;

    const table = dependencies.map(dep => ({
      packageName: dep[1], //chalk.green(dep[1]),
      currentVersion: dep[2],
      wantedVersion: dep[3],
      latestVersion: dep[4]
    }));

    console.table(table);
  });
});
```

**Comment by schnerd** [comment]
My team is currently using the following snippet
```js
return npmCheck().then(function(results) {
	var valid = true;
	for (var prop in results) {
		if (results[prop].notInstalled) {
			console.log( chalk.red('Package "' + prop + '" is not installed. Consider running ') + chalk.green('npm install') );
			valid = false;
		} else if (results[prop].mismatch) {
			console.log( chalk.red('Package "' + prop + '" is invalid. Consider running ') + chalk.green('npm install') );
			valid = false;
		}
	}
	if (!valid) {
		process.exit(1);
	}
}, function() {
	console.log( chalk.red('Couldn\'t check NPM modules') );
	process.exit(1);
});
```
This is less than ideal since it still requires a network connection to check the registry for updates, so I agree it would be awesome to have a streamlined offline version that just checks if your node_modules fulfills the package.json requirements.

@vitalets i might take a stab if you haven't started anything yet

**Comment by vitalets** [comment]
@schnerd 
it would be great! 
I still can't find time for that. I will be watching this issue and waiting for updates..
Thanks!

**Comment by vitalets** [comment]
hi @schnerd !
any news on this?

**Comment by schnerd** [comment]
@vitalets unfortunately not. work has been keeping me busy and the snippet i shared previously is working well enough for our team, so I haven't been personally incentivized to create a PR for this

**Comment by vitalets** [comment]
hi all, I found existing solution:
https://github.com/mgol/check-dependencies

for example:
```
Running "checkDependencies:check" (checkDependencies) task
>> babel-core: installed: 6.9.0, expected: ^6.10.0
>> Invoke npm prune and npm install to install missing packages and remove excessive ones
Warning: Task "checkDependencies:check" failed. Use --force to continue.
```

I think this issue can be closed.

**Comment by schnerd** [comment]
@vitalets nice find, your google-fu is strong. just tested and it works great, agree that this can be closed.
