### ISSUE TITLE
Option to check that package.json deps match node_modules deps

### ISSUE THREAD

**Issue by eyalw** [dylang/npm-check#82]
- I work with a team, they upgrade modules and install new ones. 
- Then I git-pull, run my code, and it breaks.
-- if it's easy, the error will say I'm missing a module
-- if it's not, a dependency version has been bumped up and my code will break and no indicative warning will show up.

How about adding an option to run npm-check programatically at the start of my code and have it make sure node_modules match package.json?

what do you think?

**Comment by eyalw** [comment]
This is the exact code, i commented the lines that caused the bad behavior (refetching without change to url)

![image](https://cloud.githubusercontent.com/assets/608669/13044655/f6098f9c-d3d7-11e5-930b-ee3492ef3b69.png)

**Comment by vitalets** [comment]
It seems to be the same as https://github.com/dylang/npm-check/issues/79
