### ISSUE TITLE
Does not detect old modules

### ISSUE THREAD

**Issue by onury** [dylang/npm-check#83]
I keep getting "Your modules look amazing. Keep up the great work." although I have many old node modules in the project. This only happens with one of my projects, others work fine but I don't know what the issue might be.

for example, 
I have mysql module v2.3.2
the latest is v2.10.2

I run `$ sudo npm-check -u` under the root directory that includes the package.json and node_modules.

excellent module, btw.

**Comment by dylang** [comment]
Thanks for the issue @onury. 

Can you provide the `package.json` you are using, and the output from `npm-check --debug`? Thanks!

**Comment by onury** [comment]
Ah, it seems there was an issue with my package.json (modified by a grunt task). :point_up:
So never mind. Thanks anyway.
