### ISSUE TITLE
package version pinning

### ISSUE THREAD

**Issue by tjaartvdwalt** [dylang/npm-check#84]
Is it possible to pin a package to a specific (major) version?

My example is jquery. I use a framework that is not compatible with jquery `2.x.x`, so I have to set my package.json to `1.x.x`. This means that whenever I run `npm-check` I get a "Major update available" when really want the positive reinforcement of "Your modules look amazing".

Alternatively, is it possible to exclude a certain package from npm-check?

**Comment by dylang** [comment]
Good idea for a feature. How would you like to pin the version?  A new section in the `package.json`?

**Comment by tjaartvdwalt** [comment]
I have been thinking about this issue. Please correct me if what I propose does not make sense in a `npm-check` context.

A new section in `package.json` would certainly be an option, but it does not feel very DRY. Instead I was wondering if `npm-check` should respect the way I defined my semantic versions. I will try to explain what I mean with an example:

If I have jquery `1.0.0` installed, and I have the following in my `package.json`
`"jquery": ">1.0.0"` or
`"jquery": "*"` or
`"jquery": "1.0.0-3.0.0"`
the [semver rules](https://docs.npmjs.com/misc/semver) will match `2.0.0`. In these cases it makes sense that `npm-check` should warn me that a new major version is available.

If however I have:
`"jquery": "1.0.0"` or
`"jquery": "^1.0.0"` or 
`"jquery": "~1.0.0"`
I have written my versions in such a way as to to limit the major version to `1`. Technically `2.0.0` does not match, and `npm-check` should not warn me that a new major version is available.

The problem I can see with this approach is that node uses ^ranges by default. `npm-check` would not warn the typical user of a major update even though he might want the upgrade.
