### ISSUE TITLE
Incorrect npm version on Mac OS X

### ISSUE THREAD

**Issue by xapou** [dylang/npm-check#85]
Having installed node via Homebrew with the --without-npm option and then npm, I have the following setup which works fine:

```shell
ixav:~ xp$ which node
/usr/local/bin/node
ixav:~ xp$ node --version
v4.2.1
ixav:~ xp$ which npm
/Users/xp/.node/bin/npm
ixav:~ xp$ npm --version
3.7.2
ixav:~ xp$ which npm-check
/Users/xp/.node/bin/npm-check
```
but when I run npm-check, i get this:

```shell
ixav:~ xp$ npm-check -g

npm   😎  MAJOR UP  Major update available: https://docs.npmjs.com/
                   npm install --save npm@3.7.2 to go from 2.14.7 to 3.7.2

Use npm-check -u -g for interactive update.
```
Not sure where this 2.14.7 version comes from...

**Comment by dylang** [comment]
Interesting issue!

I use https://github.com/jonschlinkert/global-modules to figure out the path for your global modules. Can you see if that module gives you the correct path? If it doesn't, create a bug for Jon and mention this issue so I can follow the progress.

**Comment by xapou** [comment]
@dylang: this seems to be a known bug in @jonschlinkert's global-prefix. [see Issue](https://github.com/jonschlinkert/global-prefix/issues/3)

**Comment by jonschlinkert** [comment]
yes, sorry. had the flu this past week, just getting caught up. this issue is near the top of my list. I should be able to fix in the next day or two.

**Comment by dylang** [comment]
Most likely related to #87 so closing this one just to keep things clean.
