### ISSUE TITLE
Possible improvement, detecting babel-eslint in package.json

### ISSUE THREAD

**Issue by LinusU** [dylang/npm-check#88]
When I run `npm-check`, in many of my projects I get the following warning:

```text
babel-eslint         😕  NOTUSED?  Possibly never referenced in the code.
                                   npm uninstall --save-dev babel-eslint to remove.
```

How do you feel about adding an additional check for used dependencies? In this case the `standard.parser` field in the `package.json`. It refers an npm module that will be used as the parser.

I understand that this might be outside of the scope for this module, but I think it would be really nice to have it :raised_hands:

**Comment by loris** [comment]
It also fails to detect that eslint plugins are properly installed, it would need to parse `plugins` and `extends` values in `.eslintrc` or `package.json` files which me be out of scope, yeah.

![](https://dl.dropboxusercontent.com/spa/tqch4axi0t55dpk/d230q462.png)

**Comment by lijunle** [comment]
@loris Try run `npm upgrade -g`, ESLint support is implemented.

**Comment by lijunle** [comment]
@LinusU How do you use the `babel-eslint` package? How you please provide more details?

**Comment by LinusU** [comment]
It's being used by eslint, a style checking utility, via the package standard.

https://github.com/feross/standard

Standard reads the value of the field `standard.parser` in my package.json file.

**Comment by loris** [comment]
@lijunle I’m already running `4.1.4`

**Comment by lijunle** [comment]
npm-check is leveraging depcheck to do unused check. The ESLint is supported as of [`depcheck@0.5.10`](https://github.com/depcheck/depcheck/releases/tag/0.5.10).

**Comment by lijunle** [comment]
@LinusU Your cases is not supported yet. I will start on it if I have time. (Sorry, I am quit busy recently.)

**Comment by LinusU** [comment]
@lijunle Thank you :heart: 

Do you want me to open an issue on depcheck?

**Comment by lijunle** [comment]
@LinusU I am opening. :)

**Comment by LinusU** [comment]
Nice :ok_hand:
