### ISSUE TITLE
Skip packages with local paths

### ISSUE THREAD

**Issue by adamkiss** [dylang/npm-check#97]
`npm-check` should ignore packages that are defined with Local Paths (via `"pkg": "file:src/my/package.js"`) – [NPM docs on Local paths](https://docs.npmjs.com/files/package.json#local-paths).

Instead, it results with `NPM ERR!` for these packages.

I tried to PR this, but the code level is currently above my level. :disappointed:

**Comment by dylang** [comment]
Good idea, and I should have thought of that, I created the pull request for `npm` that added `file:` support. :smile:

> I tried to PR this, but the code level is currently above my level. :disappointed: 

Don't blame yourself, it's not easy to follow or read, and there are practically no comments. 
Fun fact: I wrote this to get better with promises. There's still a lot I could be better with that might make this easier to read.

**Comment by adamkiss** [comment]
> Good idea, and I should have thought of that, I created the pull request for npm that added file: support. :smile:

:smile:
