### ISSUE TITLE
Many lines printed in terminal during "npm install" step if package names wrap to the next line

### ISSUE THREAD

**Issue by ide** [dylang/npm-check#98]
I ran an interactive update and npm-check started installing newer versions of some of my dependencies like this:

```
⠼ npm install babel-cli@6.6.5 babel-preset-es2015@6.6.0 babel-preset-react@6.5.0
```

My terminal wasn't wide enough to fit all of the package names, though, so they wrapped to the next line. npm-check then started printing out a new line each time it advanced the spinner animation instead of overwriting the current line.

Platform: OS X El Cap with the built-in Terminal.app.

**Comment by dylang** [comment]
This sounds like an issue for [ora](https://github.com/sindresorhus/ora), I'll create an issue there.
